02876 am a22002893u 4500
001 usp000000468
020 $a 0123456789
024 7 $a 10.1234/pusp.8 $2 doi
042 $a dc
100 10 $a Papavero , Nelson, $e author
245 10 $a Considerações sobre os felinos do velho mundo tratados como &quot;onças&quot;: notas históricas e etimológicas
260 $b USP Open Books Portal, $c 2023.
300 $a 1 online resource
500 $a 10.1234/pusp.8
500 $a http://0.0.0.0:8888/index.php/portaldelivrosUSP/catalog/book/8
506 0 $a Free-to-read $f Unrestricted online access $2 star
520 $a Os autores europeus promoveram uma considerável confusão sobre a identidade do felino denominado onça (lonza e outras variantes). Sob este nome foram incluídos o leopardo ou pantera (Panthera pardus (Linnaeus, 1758)), a chita ou guepardo (Acinonyx jubatus (Schreber, 1775)), o lince (Lynx lynx (Linnaeus, 1758)) e o caracal (Caracal caracal (Schreber, 1776), sendo ainda incluída nessa lista a hiena (Hyaena hyaena (Linnaeus, 1758)). O leopardo foi considerado um híbrido entre o leão (leo) e um felino mítico, o pardo (pardus) e diferente da pantera. Por vezes a lonza foi tratada como uma quarta espécie distinta e, por sua vez, atribuída a mais um caso de hibridação. Um apanhado da literatura sobre esses vários animais, desde a Antiguidade, até o século XIX é apresentado. As hipóteses sobre a etimologia dos diversos nomes desses felinos são comentadas. As mais prováveis são as seguintes: (i) para pardo: do sânscrito pṛdākuh (पृदाकु); (ii) para leopardo: do latim leo + pardus, baseado na ideia errônea de ser este animal um híbrido dessas duas espécies; (iii) para pantera: do Sânscrito puṇḍarīka (पु'डर*क); (iv) para lonza: de leontia; a derivação de lynx, comumente aceita, deve ser descartada, por terem o leopardo (ou pantera) e o lince propriamente dito diferentes folclores e aparências; (v) o nome chita, para o Acinonyx, foi publicado pela primeira vez por Garcia d’Orta (1563), por ele registrado na Índia; (vi) para caracal: do turco qarah-qoulaq = orelha preta ( =preto, = orelha); (vii) finalmente, para guepardo - sua designação provém da Língua Franca Mediterrênea ou Sabir gattopardo, alterado para gapardus, gapar(d) e guépard, sendo esta última forma devida a Buffon (1765), que a obteve dos peleteiros parisienses; através da influência de Buffon, o vocábulo passou para as línguas latinas modernas. Palavras-chave: Leopardo, Pantera, Onça, Lince, Caracal, Chita ou Guepardo, Histórico, Hipóteses Etimológicas.
655 7 $a Livro $2 local
786 0 $n Portal de Livros Abertos da USP;
786 0 $n USP Open Books Portal;
793 0 $a Portal de Livros Abertos da USP
856 40 $z Free-to-read: $u http://0.0.0.0:8888/index.php/portaldelivrosUSP/catalog/book/8 $7 0
949 $a Electronic resource $w ASIS $m ONLINE $k ONLINE $l ONLINE $o USP OA harvest 471 records 20210803 $r Y $s Y $t ONLINE
997 $a BSLW: DO NOT PROCESS.
596 $a 42
926 $a ONLINE $b ONLINE $c Electronic resource $d ONLINE $f 1

*******************************************

Total de caracteres am a22002893u
4500 UM BILHÃO DE NÚMEROSusp000000468 a01234567897 a10.1234/pusp.82doi  adc10aPapavero , Nelson,eauthor10aConsiderações sobre os felinos do velho mundo tratados como &quot;onças&quot;: notas históricas e etimológicas  bUSP Open Books Portal, c2023.  a1 online resource  a10.1234/pusp.8  ahttp://0.0.0.0:8888/index.php/portaldelivrosUSP/catalog/book/80 aFree-to-readfUnrestricted online access2star  aOs autores europeus promoveram uma considerável confusão sobre a identidade do felino denominado onça (lonza e outras variantes). Sob este nome foram incluídos o leopardo ou pantera (Panthera pardus (Linnaeus, 1758)), a chita ou guepardo (Acinonyx jubatus (Schreber, 1775)), o lince (Lynx lynx (Linnaeus, 1758)) e o caracal (Caracal caracal (Schreber, 1776), sendo ainda incluída nessa lista a hiena (Hyaena hyaena (Linnaeus, 1758)). O leopardo foi considerado um híbrido entre o leão (leo) e um felino mítico, o pardo (pardus) e diferente da pantera. Por vezes a lonza foi tratada como uma quarta espécie distinta e, por sua vez, atribuída a mais um caso de hibridação. Um apanhado da literatura sobre esses vários animais, desde a Antiguidade, até o século XIX é apresentado. As hipóteses sobre a etimologia dos diversos nomes desses felinos são comentadas. As mais prováveis são as seguintes: (i) para pardo: do sânscrito pṛdākuh (पृदाकु); (ii) para leopardo: do latim leo + pardus, baseado na ideia errônea de ser este animal um híbrido dessas duas espécies; (iii) para pantera: do Sânscrito puṇḍarīka (पु'डर*क); (iv) para lonza: de leontia; a derivação de lynx, comumente aceita, deve ser descartada, por terem o leopardo (ou pantera) e o lince propriamente dito diferentes folclores e aparências; (v) o nome chita, para o Acinonyx, foi publicado pela primeira vez por Garcia d’Orta (1563), por ele registrado na Índia; (vi) para caracal: do turco qarah-qoulaq = orelha preta ( =preto, = orelha); (vii) finalmente, para guepardo - sua designação provém da Língua Franca Mediterrênea ou Sabir gattopardo, alterado para gapardus, gapar(d) e guépard, sendo esta última forma devida a Buffon (1765), que a obteve dos peleteiros parisienses; através da influência de Buffon, o vocábulo passou para as línguas latinas modernas. Palavras-chave: Leopardo, Pantera, Onça, Lince, Caracal, Chita ou Guepardo, Histórico, Hipóteses Etimológicas. 7 aLivro2local10a, ,eauthor0 nPortal de Livros Abertos da USP;0 nUSP Open Books Portal;0 aPortal de Livros Abertos da USP.40zFree-to-read:uhttp://0.0.0.0:8888/index.php/portaldelivrosUSP/catalog/book/870  aElectronic resourcewASISmONLINEkONLINElONLINEoUSP OA harvest 471 records20231005rYsYtONLINE  aBSLW: DO NOT PROCESS.  a42  aONLINEbONLINEcElectronic resourcedONLINEf1